# Shuffle SOAR Workflow Architecture

## Overview

Shuffle is used as the **Security Orchestration, Automation and Response (SOAR)** layer in this project.

Its primary purpose is to receive security alerts generated by Wazuh, process the alert data, and automatically distribute the incident information to downstream response systems.

The current workflow automates two actions:

1. Create an alert in **TheHive**
2. Send an **email notification** to the SOC analyst

The workflow eliminates the need for the analyst to manually copy alert information from Wazuh into TheHive or manually send an incident notification.

---

# 1. Shuffle Workflow Architecture

The implemented Shuffle workflow follows this structure:

```text
                       WAZUH
                         │
                         │ JSON Alert
                         │ HTTP Webhook
                         ▼
                ┌──────────────────┐
                │     Webhook      │
                │     Trigger      │
                └────────┬─────────┘
                         │
                         ▼
                ┌──────────────────┐
                │      Repeat      │
                │  Alert Processing│
                └────────┬─────────┘
                         │
                ┌────────┴─────────┐
                │                  │
                ▼                  ▼
        ┌──────────────┐    ┌──────────────┐
        │   TheHive    │    │    Email     │
        │              │    │              │
        │ Create Alert │    │ SOC Alert    │
        └──────────────┘    └──────────────┘
